Update 2024-2025 deadlines, links, and add new programs
chinasaokolo/csGraduateApps pull request #7
Opened 2023-11-17 00:43 UTC by marinadunn

Deadlines and web links have been updated in table for 2024-2025 PhD cycle, as well as some new program additions.

2023-11-17 01:48 UTC, chinasaokolo requested changes
Thanks for your additions. Links direct to applicant support programs and deadlines dates are for the support programs specifically, not the departmental applications.

2023-11-20 18:20 UTC, marinadunn commented
Gotcha, thanks for the heads up! Sorry I missed that- I'll implement that in the updates!

2023-11-20 19:07 UTC, marinadunn commented
Links and dates for known support programs have been fixed.

2023-11-23 03:10 UTC, chinasaokolo approved these changes

2023-11-23 03:13 UTC, merged